/**:
  ros__parameters:
    # ==========================================
    # 1. MAIN SWITCH
    # ==========================================
    # Options: 'consensus_collision', 'absolute_goal', 'dynamic_trajectory', 'anisotropic_ellipse'
    control_mode: 't1_flocking'
    
    # Options: 'circle', 'figure8'
    traj_type: 'circle'
    
    # ==========================================
    # 2. COMMON SWARM GAINS
    # ==========================================
    alpha: 1.0    # Cohesion
    beta: 2.0    # Dispersion (0.25 = 0.5m triangle)
    rho: 3.0      # Goal/Trajectory Tracking Pull
    
    # ==========================================
    # 3. MODE-SPECIFIC PARAMETERS
    # ==========================================
    # For 'absolute_goal' mode
    goal_x: 0.0
    goal_y: 0.0
    
    # For 'dynamic_trajectory' & 'anisotropic_ellipse' modes
    traj_center_x: 0.0
    traj_center_y: 0.0
    traj_radius: 1.0
    traj_w: 0.08
    
    # For 'anisotropic_ellipse' mode
    m11: 1.0             # Strong repulsion along major axis
    m22: 1.0             # Weak repulsion along minor axis
    is_rotating: False    # True = steers with path, False = uses fixed angle
    ellipse_alpha: 0.0  # Fixed angle (rad) if is_rotating is False
    
    # ==========================================
    # 4. KINEMATICS & LIMITS
    # ==========================================
    b: 0.1
    max_v: 0.18
    max_w: 1.5

    K: 2.0                 # <--- ADDED HERE
    y_bar: 1.0           # <--- ADDED HERE
    safe_dist: 0.30         # <--- ADDED HERE